name: mut_sigs
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pymc>=4
  - seaborn
  - arviz
  - pandas>=1.0
  - numpy
  - jupyter
  - jupyterlab
  - tqdm
  - pysam
  - snakemake>=7.8.5
  - unzip
  - openpyxl